name: Create UAT Fix PR

on:  workflow_dispatch

jobs:
  create-uat-fix-pr:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create new branch
        run: |
          git fetch origin uat
          git checkout -b uat_fix origin/uat
          git push origin uat_fix

      - name: Pull request létrehozása GitHub CLI-vel
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
        run: |
            gh pr create --title "Automatikus PR a UAT Fix branch-ről" \
                         --base production \
                         --head uat_fix \
                         --template "./.github/pull_request_template.md"
