name: Create UAT Fix PR

on:  workflow_dispatch

jobs:
  create-uat-fix-pr:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create new branch
        run: |
          git fetch origin uat
          git checkout -b uat_fix origin/uat
          git push origin uat_fix

      - name: Pull request létrehozása
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.MY_GITHUB_PAT }}
          base: uat_fix
          branch: production
          title: "Automatikus PR a UAT Fix branch-ről"
          body: "Ez egy automatikus PR az origin/uat-ból létrehozott uat_fix branch-ből az origin/production-ra."
