name: Create PR from UAT to Production

on: workflow_dispatch

jobs:
  create-uat-fix-pr:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create new branch
        run: |
          git fetch origin uat
          git checkout -b release/release_uat_fix origin/uat
          git push origin release/release_uat_fix

      - name: Pull request létrehozása GitHub CLI-vel
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}
        run: |
            gh pr create --title "UAT to Production" \
                         --body "$(cat ./.github/pull_request_template.md)" \
                         --base production \
                         --head release/release_uat_fix \
