name: Create UAT to Production Pull Request

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions interface

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out your repository code

      - name: Create Pull Request from UAT to Production
        uses: peter-evans/create-pull-request@v7  # Specify the current version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: production  # Target branch for PR
          branch: uat  # Source branch for PR
          title: "Merge UAT changes to Production"
          body: "This pull request merges changes from `uat` to `production`."
          draft: false  # Optional: if true, creates a draft pull request
